version: '3'
services:
  app_test:
    container_name: toko_kocak_test
    build: 
      context: .
      dockerfile: ./Dockerfile.test
    env_file:
      - .env
    ports:
      - 8081:8080
    restart: always
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - postgres_test
      - redis_test
    networks:
      - apinetwork
        
  postgres_test:
    image: postgres:latest
    container_name: db_tokokocak_test
    ports:
      - 4321:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD_TEST}
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_DB=${DB_NAME_TEST}
    volumes:
      - database:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - apinetwork
        
  redis_test:
    image: redis:6.2-alpine
    restart: always
    container_name: tk_redis_test
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass konohagakure
    volumes: 
      - cache:/data
    networks:
      - apinetwork
volumes:
  database:
  cache:

networks:
  apinetwork:
    driver: bridge

    