version: '3'
services:
  app:
    container_name: toko_kocak
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - postgres
      - redis
    networks:
      - apinetwork
        
  postgres:
    image: postgres:latest
    container_name: db_tokokocak
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database:/var/lib/postgresql/data
      - ./db/db-prod:/docker-entrypoint-initdb.d/
    networks:
      - apinetwork
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass konohagakure
    volumes: 
      - cache:/data
    networks:
      - apinetwork
volumes:
  database:
  cache:

networks:
  apinetwork:
    driver: bridge

    